image: python:3.7

clone:
  depth: full # SonarCloud scanner needs the full history to assign issues properly

definitions:
  services:
    docker:
      memory: 3072
  steps:
  - step: &release
      name: Creates a release (increment version, add tag, commit and push)
      script:
      - git config --global user.email "$GIT_RELEASE_BOT_EMAIL"
      - git config --global user.name "$GIT_RELEASE_BOT_NAME"
      - git remote set-url origin https://$GIT_ACCOUNT_USER:$GIT_ACCOUNT_PASS@bitbucket.org/$BITBUCKET_REPO_OWNER/$BITBUCKET_REPO_SLUG.git
      - pip install python-semantic-release
      - semantic-release version
      - git push --tags
      - git push
  - step: &publish
      name: Creates a distribution of the package and uploads to our PyPI server
      script:
      - pip install twine
      - python setup.py sdist
      - twine upload --repository-url https://$PYPI_URL --username $PYPI_USER --password
        $PYPI_PASSWORD dist/*
  - step: &tox
      name: Automated tests and code checking
      script:
      - apt-get -y update
      - apt-get install -y python3.7-dev
      - pip install tox
      - tox
  - step: &build-sonarcloud
      name: Run tests coverage and Build/test/analyze on SonarCloud
      script:
      - apt-get -y update
      - apt-get install -y python3.7-dev
      - pip install tox
      - tox -e coverage
      - pipe: sonarsource/sonarcloud-scan:1.0.1
      - pipe: sonarsource/sonarcloud-quality-gate:0.1.3

pipelines:
  branches:
    master:
    - step: *build-sonarcloud
    - step: *release
    feature/*:
      - step: *tox
  pull-requests:
    '**':
    - step: *build-sonarcloud
    - step: *tox
  tags:
    v*.*.*:
    - step: *publish
