version: '3.4'

services:
  erste-replica-db:
      container_name: erste-replica-db
      image: mongo:latest
      hostname: mongodb
      expose:
       - 27018
      ports:
       - '27018:27017'
      restart: always
      environment:
       - MONGO_INITDB_ROOT_USERNAME=root
       - MONGO_INITDB_ROOT_PASSWORD=root
       - MONGO_INITDB_DATABASE=admin
       - MONGO_REPLICA_SET_NAME=replica0
      healthcheck:
        test: test $$(echo "rs.initiate().ok || rs.slaveOk().ok || rs.status().ok" | mongo --quiet) -eq 1
        interval: 10s
        start_period: 30s
      entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--replSet", "replica0" ]
      volumes: 
        - ./mongo-initdb.d:/docker-entrypoint-initdb.d
