eureka:
    client:
        fetchRegistry: true
        registerWithEureka: true
        service-url:
            default-zone: http://localhost:8761/eureka/
    server:
        wait-time-in-ms-when-sync-empty: 0
logging:
    file: ./log/zuulGatewayService.log
server:
    port: 8766
spring:
    application:
        name: zuul-gateway
    data:
        mongodb:
            database: Oauthdb
            authentication-database: admin
            username: root
            password: root
            host: localhost
            port: 27017

   
security:
    user:
        password: password
    oauth2:
        resource:
            filter-order: 3
    permitAll: true

audit:
    storageEngine: mongoDB   