spring:
   data:
      mongodb:
        authentication-database: admin
        username: root
        password: root
        database: QANDA
        port: 27017
        host: localhost   

# Eureka integration config
eureka:
  instance:
    hostname: localhost
    port: 8761
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${eureka.instance.port}/eureka